development:
  adapter: postgresql
  encoding: utf8
  database: hatorade_development
  pool: 5
  username: VoodooLogic
  password:
  port: 5432

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: hatorade_test
  pool: 5
  username: VoodooLogic
  password:
  port: 5432

production:
  adapter: postgresql
  encoding: utf8
  database: hatorade_production
  pool: 5
  username: VoodooLogic
  password:
  port: 5432

cucumber:
  <<: *TEST
